### ISSUE TITLE
scientific tif options

### ISSUE THREAD

**Issue by Tokariew** [nsxiv/nsxiv#116]
Would be possible to add some additional support for tif files? Mainly

- support for float data inside image
- multipage support

If yes, I can provide test images for it.

**Comment by Tokariew** [comment]
I will agree that i used `scientific tiff` quite loose… But look at OME-TIFF or GeoTIFF - they use tiff format with something else than 8 bit unsigned int per channel.
Multipage – tiff can have multiple images in them, with different dimensions and data types. Each image is in new `Image File Directory` Look on tiff documentation under `NewSubfileType` -- you can see that they call them multi-page images.
Currently sxiv only display first image ignoring the rest of pages in tiff.

`BitsPerSample` `SamplesPerPixel` and `SampleFormat` --specify format of data.
Currently nsxiv will fail with images with uint32 data and any float data inside.

but not sure if imlib2 even support float data inside images

**Comment by N-R-K** [comment]
> Currently sxiv only display first image ignoring the rest of pages in tiff.

That's due to imlib2. imlib2 doesn't support multi-frame images, so we have our own loader for animated gif and webp. Adding a similar loader for tiff is in the [TODO](https://github.com/nsxiv/nsxiv/blob/master/TODO.md) list. PR is welcomed.

> But look at OME-TIFF or GeoTIFF - they use quite often tiff format with something else than 8 bit unsigned int per channel.

Support for single frame images (and new formats) should go into imlib2. If imlib2 supports it then nsxiv will as well without needing any modification on our end.

**Comment by N-R-K** [comment]
Closing, see: #192
