### ISSUE TITLE
Can't use XK_bar as a shortcut in config.h

### ISSUE THREAD

**Issue by Dupond** [nsxiv/nsxiv#123]
Hello,

As the title says, the default `XK_bar` keybind defined in my `config.h` doesn't work.

Here are the things that I've tried:

1. I fully reinstalled `nsxiv` in order to be 100% sure that there's no custom modification involved; I installed it using the following commands:

```
git clone https://github.com/nsxiv/nsxiv
cd nsxiv/
sudo make clean install
```

2. So I use the default `config.h` file; it still doesn't work;
3. I then tried to replace `XK_bar` with `XK_X` and it works: the image is flipped horizontally when I press `X`; so it's definitely a problem with the `XK_bar` key, not the image itself, or anything else;
4. I can write a bar in my terminal using `Alt Gr` followed by the `6` key (no shift needed); nevertheless, I've tried all the combinations I could think of, but none has worked (AltGr-Shift-6, AltGr-6, Alt-6, etc.)

I use Arch, if that matters. Is there anything else that I should try? Thanx in advance for any help!

**Comment by TAAPArthur** [comment]
I wonder if nsxiv is receiving an additional modifier instead of just a plain '|'. Unlike sxiv, we don't white list modifiers, we blacklist them.

If you have xev installed, mind sharing the output of `xev -event keyboard` while pressing the the key in question. Just the paragraph with the '|' being pressed will do.  Example output:
```
KeyPress event, serial 28, synthetic NO, window 0x4400001,
    root 0x7ab, subw 0x0, time 185604456, (437,673), root:(437,691),
    state 0x1, keycode 51 (keysym 0x7c, bar), same_screen YES,
    XLookupString gives 1 bytes: (7c) "|"
    XmbLookupString gives 1 bytes: (7c) "|"
    XFilterEvent returns: False
```

If you don't have it installed and don't want to install it you could modify nsxiv instead. In main.c::on_keypress, you can add `printf("Mod: %d Key %c\n", kev->state, key, key);` right after XLookupString and share this output. I believe you'll see something non-zero for the modifier. 

In either method, if you see some modifier (some non-zero state) being sent along with '|', add that to `ignore_mask` in config.def.h or modify/copy the default binding to include this modifier.

**Comment by Dupond** [comment]
Thanx for helping.

When I press the `AltGr` key, `xev -event keyboard` outputs the following:

> KeyPress event, serial 28, synthetic NO, window 0x2200001,
>     root 0x6de, subw 0x0, time 34269435, (737,533), root:(738,585),
>     state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
>     XKeysymToKeycode returns keycode: 92
>     XLookupString gives 0 bytes:
>     XmbLookupString gives 0 bytes:
>     XFilterEvent returns: False

Then I press the `6` key and have this:

> KeyPress event, serial 28, synthetic NO, window 0x2200001,
>     root 0x6de, subw 0x0, time 34269532, (737,533), root:(738,585),
>     state 0x90, keycode 15 (keysym 0x7c, bar), same_screen YES,
>     XLookupString gives 1 bytes: (7c) "|"
>     XmbLookupString gives 1 bytes: (7c) "|"
>     XFilterEvent returns: False

I'm not sure where the modifier is displayed; should I try to add `ISO_Level3_Shift` as a modifier to the default binding?

**Comment by TAAPArthur** [comment]
Maybe [here](https://wiki.archlinux.org/title/Xmodmap) or [here](https://tronche.com/gui/x/xlib/input/keyboard-encoding.html). The list of modifiers are defined in /usr/include/X11/X.h on arch by default. Basically modifiers like Shift, Control and Alt are bits in a key state and the set of bits sets indicates the set of modifiers that are active. While those 3 may be common there are 8 of them and they keys they map to vary between systems (technically this is true for any keys).

**Comment by Dupond** [comment]
Thanx for the explanation!

**Comment by N-R-K** [comment]
Since this somewhat breaks backwards compatibility (atleast for one user so far) I'm considering this a "bug" and reopening.

> blacklist everything other than `ShiftMask ControlMask Mod1Mask` by default

Also since this is now a config variable, `ignore_mask`, users can just change it if they want. I'm not seeing much downside in this.

**Comment by TAAPArthur** [comment]
I'd vote no for 3 reasons.
First the OP seems to be content with just changing the config variable. Or at least I'm not under the impression he's requesting us to change the default.
Second I saw the sxiv's behavior as a bug that was fixed. Arbitrarily choosing those 3 modifiers and hiding the others doesn't make since to me and don't believe it is a common practice. We could run into the opposite case where someone used Mod4 + bar and wounder why it didn't work. Granted in this latter case the user is already in the config file but believe the primary audience is those compiling from source so don't think it really makes a difference
Finally keeping sxiv's default behavior isn't a priority to me. From my view, we break/change behavior all the time. And if we think the old behavior is bad, I don't see that as a problem, especially if the old end result can still be achieved. Our behavior diverged from sxiv but became more consistent with most other things (like st/dwm).

**Comment by TAAPArthur** [comment]
I get where you're coming from. I'm just pointing out that I believe that this "issue" isn't unique to us and that I don't really see it as a problem. Technically one could get around this with xmodmap and/or changing their default layout without compiling from source but that's kinda heavy handed. I also think it is equally valid that that one may want the bindings to be separate. For example imagine there was a program listening on Mod4 + | and the user didn't want to flip the image every time nsxiv was in focus and they want to signal that program.

It isn't that I think what you're suggesting is unreasonable. I had considered it when first submitting that PR. I just think it is a worse default. And I don't really want to change defaults from what I view as an ideal just to support binary users. Instead, I'd rather give them some options like those in https://github.com/nsxiv/nsxiv/issues/108 (specifically option 1) because it covers the more general case of users not liking the set of default bindings/config options.

Side note, if the issue wasn't with bar but with "A" and the user wanted to differentiate between this "A" and Shift + "a"... this is where https://github.com/nsxiv/nsxiv/pull/78

Another side note: Should we be applying ignore_mask to the key_handler? Current it doesn't matter by default since the key handler only passes in those 3 modifiers (and maybe this should be extended?), but technically one could set it to Shift, Control or Alt and I believe one would expect those modifiers to not appear in the script
