### ISSUE TITLE
Dedicated library for multiframe images

### ISSUE THREAD

**Issue by TAAPArthur** [nsxiv/nsxiv#128]
So my fear is that we are going to bloat nsxiv trying to support every image format under the sun and that should be delegated to a dedicated library. We use imglib for most things and believe will reject any PRs where imglib will add support itself. However, we seem to be on our own when it comes to multi frame images. We have custom loaders for gif and webp and seem to want more formats like animated tif and png. 

Just for some context, image.c is ~900 lines and about of third of it relates to loading gifs/webp. And reading some of the descriptions of the open PRs, think other image formats are going to be more work.

Is there a reason we don't just have a dedicated library for it? I imagine we don't want to fork imglib and/or there's a good reason why they don't want to support animated image. But couldn't we have some libaimglib in this org that just holds all existing (and future) image loader code. Either as a git sub-module or a dedicated optional dependency. Hey maybe it is good enough as a standalone file in this repro until it gets big enough. Aside from the code separation, I think a main benefit is to provide a generic lib for animated image formats that could be reused for other programs instead of having everyone re-invent the wheel. 

This relates to #122, #126, #65, #20

**Comment by N-R-K** [comment]
Not against the idea of creating a dedicated library for multi-frame images, but I don't consider it to be high priority.

> Either as a git sub-module or a dedicated optional dependency.

However I'd like to avoid this. Just adds one extra dep the user will have to fetch. At least until a good number of other projects also use this library, making it a shared lib has no benefits.

- - -

Also instead of getting too ahead of ourselves, it might be better to look up what imlib2's stance on multi-frame images are. If they're willing to accept patches then that should be the preferred way instead of writing our own wrapper lib.

**Comment by TAAPArthur** [comment]
>Also instead of getting too ahead of ourselves, it might be better to look up what imlib2's stance on multi-frame images are.

Fair but on the same level, isn't adding custom loaders to nsxiv getting ahead of ourselves?  I agree it is better if imglib takes them directly and just assumed they wouldn't and that prompted us to add them ourselves. If that assumption isn't true, then shouldn't we hold off on accepting more loaders?

**Comment by N-R-K** [comment]
Re-opening since I think there's merit to separating the multi-frame loaders into a dedicated library. I haven't looked into imlib2's stance on this though, will have to do that first.

> If that assumption isn't true, then shouldn't we hold off on accepting more loaders?

Maybe, but it's free-software development. People will work on whatever they're interested in, we can't really dictate who will work on what. If someone wants to work on another multi-frame loader, I don't think it hurts, since we should be able to re-use the code for when/if we do decide to make a library out of it.

**Comment by TAAPArthur** [comment]
They can work on whatever, but doesn't mean it should make it into master. Adding more loaders adds more default dependencies. Going to update and needing to update build flags or when on a non-source distro being "forced" into extra depends isn't ideal. So I don't see adding more loaders/dependencies as harmless.

But to the original idea, I think it should be expanded to just making imlib2 optional and being able to replace it with other loaders even for single frame images, but doubt we'd ever do it since it would break some default keybindings of flipping/rotating images.

**Comment by N-R-K** [comment]
> Adding more loaders adds more default dependencies.

Fair point, but I'm not seeing how a separate library solves this. We'll just be moving the dependency from one place to another.

> I think it should be expanded to just making imlib2 optional and being able to replace it with other loaders even for single frame images, but doubt we'd ever do it since it would break some default keybindings of flipping/rotating images.

It would also change the code-base by a significant amount. I think @GRFreire made a good point about not doing that since it would mean people already familiar with sxiv codebse would be completely lost.

**Comment by TAAPArthur** [comment]
In my eyes with the separate library, we'd never add another dependency (for image formats) after that. So then we could add every animated lib under the sun and users who don't care won't be affected... at least not those compiling from source. Ideally im2lib would just handle animated libs since we already use that for most image formats.

If there are few more relevant animated image formats, may not have benefit for this project although people forking/rewriting could benefit from not having to duplicate the code. I've looked at some of the other image viewers like meh and leh and was disappointed by the amount of shared code. And that was for just regular image loading because they probably didn't want the bloat of imlib2.

>It would also change the code-base by a significant amount. 

I'm not proposing to drop imlib2. Just stating an ideal. And the fact that that ideal wouldn't be realized here is part of the reason I lost interest in this issue. Once one is aware of it, they can just only enable the libs they want. So the only downside to them is there being large chunks of code they don't care about which is already probably true. And while I think offloading functionality to libs is nice and all, I'm doing that [here](https://github.com/TAAPArthur/libimageloader) for single frame images which can be trivially extended to multi-frame images with the write compile flags.

But since keeping imlib2 is a must, adding the animated loaders there seems like the cleanest solution for this project and making another dependency for abstraction doesn't seem that helpful.

**Comment by N-R-K** [comment]
> But since keeping imlib2 is a must, adding the animated loaders there seems like the cleanest solution for this project and making another dependency for abstraction doesn't seem that helpful.

I guess that makes sense. I was thinking having a dedicated wrapper library could be useful for other projects and reduce duplicated work.

Regardless, I've talked with Kim, the Imlib2 maintainer, and he seems to be open towards adding animated image support. So closing this.
