### ISSUE TITLE
Feature Request: Support for cbr/cbz/cbt files

### ISSUE THREAD

**Issue by fboumol** [nsxiv/nsxiv#153]
I am wondering whether there is any interest in supporting (via nsxiv or via something in nsxiv-extra) "cbr/cbz/cbt" files. I have not been able to find any information about this.

My suggestion to support them would be to have the following features:
 - in thumbnail mode show the first image of the archive (perhaps superposing some icon suggesting it is an archive),
 - in view mode (I mean when opening the archive with nsxiv) mount the archive in some temporal folder,  show thumbnails of each one the images in the archive, and later adopt the changes made in this temporary folder to the archive file (I am thinking about using the key-handler to make permanent changes in the archive: delete images, rotate images, etc)

**Comment by N-R-K** [comment]
nsxiv is an image viewer, it has nothing to do with opening archives.

If you want to open and view archives in nsxiv it should be very easy thing to do via a shell wrapper. I think @TAAPArthur was reading japanese comics with nsxiv, so he might have a script for it already.

> show thumbnails of each one the images in the archive, and later adopt the changes made in this temporary folder to the archive file (I am thinking about using the key-handler to make permanent changes in the archive: delete images, rotate images, etc)

This should not be too hard either. I can think of a couple ways to do it. Either wait for nsxiv to exit or use `trap` to automatically run the archiver and overwrite the original upon exit.

**Comment by N-R-K** [comment]
Here's a minimal (and hard-coded) script using p7zip. It should not be too difficult to extend it to other formats and/or other archivers.

```sh
#!/bin/sh

tmp="${TMPDIR:-/tmp}/comix"
trap 'rm -rf $tmp' EXIT

case "$1" in
	*.cbr) 7z x -o"$tmp" "$1" ;;
	*) echo "unsupported file" >&2 ; exit 1 ;;
esac

nsxiv -r "$tmp"
```

**Comment by fboumol** [comment]
Thanks for the suggestion, I will implement in a near future some shell script for doing so.

By the way, in case I use (n)sxiv to open a bunch of images, is is there some way to obtain (in the shell) the filename of the currently displayed image?

**Comment by N-R-K** [comment]
> is is there some way to obtain (in the shell) the filename of the currently displayed image?

As of now, no. But the topic of IPC has come up a couple times. If any of the devs are interested in picking it up then it might be possible in the future.

As a dirty hack you can use `image-info` to write the path `$1` to some tmp file. Check out the example `image-info` provided in the repo and man page section on it.

**Comment by fboumol** [comment]
At this moment the image-info trick will solve my issues. Great trick.

**Comment by N-R-K** [comment]
Also note, this hack will only work on image mode since `image-info` isn't used in thumbnails mode. An issue for applying `image-info` to thumbnail mode as well is open an up for grabs #88

**Comment by TAAPArthur** [comment]
> If you want to open and view the contents of an archives in nsxiv it should be very easy thing to do via a shell wrapper. I think @TAAPArthur was reading japanese comics with nsxiv, so he might have a script for it already.

One thing to note is that cbz is literally a zip file with a different extensions. Believe the same is true for the other formats mentioned. So like suggested you could just blindly extract them into a temp directory and have nsxiv open that. Similar principle should work for epubs. I don't think it is unreasonable for nsxiv-extra to support such formats (although not as initially described), but if it is natively supported it, it would basically do the same thing (in probably many more lines). So I generally agree with @N-R-K proposal. 

I will say that [zathura](https://pwmt.org/projects/zathura/) with [zathura-cb](https://pwmt.org/projects/zathura-cb) has comic book support that should work well (if your images are the same size) and also handles text. I can't say how easy it is to script to modify the currently viewed image but it certainly isn't impossible since at the very least the image name is in the window title. 

Ironically zathura doesn't support raw images and we don't support archives but converting between the 2 is trivial


>>is is there some way to obtain (in the shell) the filename of the currently displayed image?
>
>As of now, no. But the topic of IPC has come up a couple times. If any of the devs are interested in picking it up then it might be possible in the future.

Technically there is. The image name is in the window title and you could parse that. We could have something more robust in the future if there is demand for it. Like passing the active image name to the keyhandler. If you are writing custom functions in config.h you also have access to it

**Comment by N-R-K** [comment]
> One thing to note is that cbz is literally a zip file with a different extensions.

Yes, and `.cbr` is a rar and `.cb7` is 7zip. Not sure about `.cbt` but I assume it's same situation.

> Like passing the active image name to the keyhandler

If there aren't any marked images then that's already the default behavior.

> The image name is in the window title and you could parse that.

That's possible too. But it's not too robust since the default is just the image name and not the full path, more efficient than the `image-info` hack though. But also not guaranteed to work on custom configs where image name on title is disabled.

**Comment by XPhyro** [comment]
@fboumol We've enabled issues in [nsxiv-extra](https://github.com/nsxiv/nsxiv-extra). If you're still interested in this feature, you can submit a patch/script request and someone may implement it.

**Comment by TAAPArthur** [comment]
You could also check out some of the [related projects](https://github.com/nsxiv/nsxiv#related-projects) some of which have native support for archives.

**Comment by fboumol** [comment]
Let me say that after some time playing around with this topic I have found a very efficient solution. The trick is to use:
 - the wonderful [avfs](http://avf.sourceforge.net/) (it deserves to be much more known), together with
 - the following shell function
   `cbview() { mountavfs; { for i in "$@"; do [ ! -e "$i" ] && echo "cannot find... ${i}" > /dev/stderr && continue; j=~/.avfs"$(readlink -f "${i}")"\#; j="$(echo "$j" | sed -e "s/.cbz#$/.cbz#uzip/" -e "s/.cbr#$/.cbr#urar/" -e "s/.cb7#$/.cb7#u7z/" -e "s/.cbt#$/.cbt#utar/" -e "s/.epub#$/.epub#uzip/" )"; [ -d "$j" ] && { find "$j" -type f -print0 | sort -z -V ; true; } || printf "%s\0" "$i"; done; } | xargs -0 nsxiv -t -s d ; }`

Some usage examples to illustrate the role of the previous function are:
`cbview file1.cbz`
`cbview file1.epub`
`cbview file1.cbz image1.jpg file2.cbz`
`cbview file2.cbz image1.jpg file1.cbz`
`cbview A*.{cbz,cbr}`
`cbview *hello*.cb?`
`( shopt -s globstar nocaseglob; cbview **/*hello*.{cbz,cbr})`

Feel free to use (and modify) this trick in [nsiv-extra](https://github.com/nsxiv/nsxiv-extra) if anyone considers so.

Let me also say that anyone using this might also be interested in using a shortcut for jumping (in nsxiv navigation mode) from one comic book to the next one (or the previous one). To accomplish this take a look at [this answer by N-R-K](https://github.com/nsxiv/nsxiv/issues/207)

Let me clarify that _this trick can be trivially modified to use any other image viewer (for example, [fim](https://www.nongnu.org/fbi-improved/)) to open comic book archives (and epub)._

**Comment by N-R-K** [comment]
> I was unable to get natural sorting with the recursive flag -r provided by nxsiv, and so I am not using the recursion provided by nsxiv. Perhaps it would be nice to add as a feature to nsxiv

This was an issue on sxiv and the solution was using `sort -V` or the python script in that thread, https://github.com/muennich/sxiv/issues/229
