### ISSUE TITLE
Mage, even simpler image viewer

### ISSUE THREAD

**Issue by explosion-mental** [nsxiv/nsxiv#169]
Hello everyone!

Keeping it short, I'm working on a 'simpler version of sxiv'. Not so long ago I noticed #148 and came to the realization that it's too complex for a _simple_ program. That's why I consider sxiv to be in the middle. 
I will take WMs as examples, ignore details. 'This isn't qtile, but very similar, and this isn't dwm, but also very similar'.

So I think "mantaining" the level of complexity (keeping it in the middle) is the best approach, makes it simpler to hack on but also has 'sane' sensible features (to make it 'competent' with programs like feh).
That is the reason I post this here. I think most use sxiv without any patch (meaning adding features/modifications outside config.h) so I would consider a bad move taking features from sxiv (that's also why adding features doesn't hurt). In conclusion, having options is always great. 

Anyway, for those wanting that truely 'suckless' like image viewer, hop on!
https://github.com/explosion-mental/mage

Please suggest a better tittle for this issue.

**Comment by TAAPArthur** [comment]
So had similar thoughts and created [Dumb Image Viewer](https://github.com/TAAPArthur/div). Maybe we should have a related projects page with the pros/cons of each project?

On a related note, also created a [wrapper around image loaders](https://github.com/TAAPArthur/libimageloader) to avoid the hard imlib2 dependency because I think dependencies should be that bloated. It has support for loading every file in a directory, loading from pipes, and optionally loading from remote urls (via libcurl). The actual image loading is being done by imlib2, libspng and/or stb_image depending on how it is compiled. The main difference between imlib2 directly is that you have to render the image yourself and there's no method to generically flip, rotate images.

**Comment by N-R-K** [comment]
> Maybe we should have a related projects page with the pros/cons of each project?

It's not realistically possible for a single software to cater to all needs, so having a list of related/similar projects seems reasonable. Although I think listing pros/cons of them is a bit too much, that should be done on the respective project's README.

**Comment by TAAPArthur** [comment]
Maybe pros/cons is too much. I was thinking something like [this](https://github.com/nothings/single_file_libs). Perhaps just a one-line description.

**Comment by explosion-mental** [comment]
Very interesting @TAAPArthur.

I decided to use ImLib2 because it handle most of the things in the back, so I don't have to worry (or know) about most internal things. I supposed that's what muennich also had in mind..

`div` looks interesting, I've never seen a `--recompile` flag!

**Comment by TAAPArthur** [comment]
`--recompile` was inspired from xmonad which behaves the same way. I like it because it gives full customization even when installing from a package manager which avoids some of the debates nsxiv has had about source vs binary users.

>I decided to use ImLib2 because it handle most of the things in the back, so I don't have to worry (or know) about most internal things. I supposed that's what muennich also had in mind..

Fair. But I think it abstracts away too much to such an extent that can cause lock-in. Also not a huge fan of the memory allocations it has just from being loaded (as reported by valgrind). I do think it is nice that it wraps libjpeg/libpng, but was disappointed that meh and lel duplicated a lot of shared code presumably because they both wanted to be minimal and avoid Imlib2. There's also the case that there are more minimal image loaders out there and Imlib2 doesn't support xcb.

**Comment by N-R-K** [comment]
@TAAPArthur I tried out div for a min or two yesterday. Zooming in and "grid mode" via `t` causes segfault and zooming out doesn't work properly and distorts the image.

I see that there's been some more commits since I've tried it, so some of the issue might already been fixed, but notifying you regardless.

**Comment by TAAPArthur** [comment]
Thanks. Yeah discovered the segfault yesterday. Not aware about the zooming issue; will look into

**Comment by explosion-mental** [comment]
> Fair. But I think it abstracts away too much to such an extent that can cause lock-in. Also not a huge fan of the memory allocations it has just from being loaded (as reported by valgrind). I do think it is nice that it wraps libjpeg/libpng, but was disappointed that meh and lel duplicated a lot of shared code presumably because they both wanted to be minimal and avoid Imlib2. There's also the case that there are more minimal image loaders out there and Imlib2 doesn't support xcb.

@TAAPArthur from what I understand `ImLib2` is '''legacy''' which menas it's only maintain for hotfixes or similar, so that could be one reason? Time to fork imlib2 I guess

**Comment by TAAPArthur** [comment]
@explosion-mental  https://github.com/TAAPArthur/libimageloader (taking suggestions for a better name)
It isn't a fork but a simple wrapper. Meant to be a way to load images without caring what specific loader you want. Then there's also [stb_image.h](https://github.com/nothings/stb/blob/master/stb_image.h) which is just a single header image loader which supports most common formats.

**Comment by N-R-K** [comment]
> which means it's only maintain for hotfixes or similar

Looking at their [git commit log](https://git.enlightenment.org/legacy/imlib2.git/log), I don't think that's the case.

**Comment by explosion-mental** [comment]
@TAAPArthur yeah seen it, I don't like `libzip` there tho.

Could you elaborate more about this library? To be honest I don't like the word `simple` and `wrapper` toghether, but I see the point. Saying this because I haven't tried to render an image with plain X tools, maybe it is easier but my point is: 
if we have a much easier / abstract wrapper for loading images `imlib2` what does you lib brings to the table?

**Comment by explosion-mental** [comment]
> Looking at their git commit log, I don't think that's the case. There's active refactoring and other changes going on. They recently added support for animated webp as well , see #162 .

@N-R-K interesting, so it supports animated webp but.. no gifs? I've only seen like 2 or 3 webp animated files! outside of a web browser ofc.

**Comment by N-R-K** [comment]
> so it supports animated webp but.. no gifs?

Well, I mean it loads the first frame of animated gif and tiff, but for webp it would fail. After I filed a bug report they've fixed the issue and now it's able to load the _first frame_ of an animated webp similar to animated gif and tiff.

**Comment by TAAPArthur** [comment]
> if we have a much easier / abstract wrapper for loading images imlib2 what does you lib brings to the table?

Don't know at what point to move the conversation to that repro, ideally the benefits would be clear from the readme. The high level idea is that "loading an image" is not an interesting task and that every image loader has to basically re-implement that (see meh for an example). Of course there are dedicated libraries for common formats, but that could take a few dozen lines to integrate properly (error handling and all) which adds up after a while. And then you force your user into a certain set of dependencies. Like if you use spng for all png related things in your setup, you may not want to instead libpng or Imlib2. 

I also don't think the imlib2 is easier to use if you are just loading images. It is more featureful, but alot of its features are well past simply loading an image (rotation, rendering etc). Scaling is one nice feature of it and was thinking of adding a scaling option, but stb_image_resize already exists and didn't see a need to duplicate and something something UNIX philosophy. 

I haven't benchmarked it myself, but these alternative loaders generally claim that they are faster (and safer) than their mainstream counterparts and they are certainly smaller. 

It also handles cases that are related to image loading like loading from archives, remote urls, stdin/pipes and directories all of which are common features requested at some point for nsxiv/sxiv and were rejected because of the extra complexity. Making it part of the wrapper, gives the end user more features without any extra effort of the developer. Of course, literally every dependency is optional and if not installed will automatically be disabled. And each dependency is basically its own isolated file, so didn't see downsides to being liberal and adding "extra" ones like libzip (although I also added miniz as a replacement) since I didn't see it as hurting readability.

But to answer your question, if you are fine with having Im2lib and so are all your users, there isn't much to gain besides the new easy of switching to a different lib and/or use multiple libs (like being able to support more formats besides what Im2libs gives you without extra work). 

>Saying this because I haven't tried to render an image with plain X tools

It is 3 lines once you extract the raw data... if you just want to render.

**Comment by explosion-mental** [comment]
> Well, I mean it loads the first frame of animated gif and tiff, but for webp it would fail. After I filed a bug report they've fixed the issue and now it's able to load the _first frame_ of an animated webp similar to animated gif and tiff.

Oh, so the 'animated format' loading is/was managed by a loader made by muennich? since it loads the first frame, could it load the 2nd one by being recursive? I haven't implemented support for gifs so no investigation on my part about how is it done, so excuse my questions.

**Comment by explosion-mental** [comment]
@TAAPArthur Wow. If you don't mind, could you make a simple example on how to use your library? I'm very practical but docs are also good. Similar to [imlib2 example](https://docs.enlightenment.org/api/imlib2/html/).
Another thing. Can you tell if by using this lib, do I lose the ability (feature) to cache?

**Comment by explosion-mental** [comment]
> It is 3 lines once you extract the raw data... if you just want to render.

really? giving `lel` a quick view looks like `X{Create,Init,Put}Image`¿?

I remember I got scared by looking at dwm winicons patch, I guess it uses imlib2 so it isn't really _raw Xlib_..

**Comment by TAAPArthur** [comment]
>@TAAPArthur Wow. If you don't mind, could you make a simple example on how to use your library? I'm very practical but docs are also good. Similar to imlib2 simple/complex example.

Yeah I'm going to add documentation... eventually. Right after I standardize method/var naming. The best examples are going to be in div. [defaults.c](https://github.com/TAAPArthur/div/blob/master/defaults.c) has all the interesting uses including creating the context and actually opening the images. x.c does the actual rendering but that is just passing the data pointer to xcb_image_create (basically). Can also link my [config file](https://github.com/TAAPArthur/SystemConfig/blob/master/Config/.config/div/config.c) which also has examples of how to using the sorting features (and better scaling functions)

And for anyone wanting to not use im2lib but use a dedicated loader directly (ie libpng, libspng, etc), be aware that native png format has the red and blue bytes flipped from how you may expect see [RGBA8888 vs ARGB32](https://en.wikipedia.org/wiki/RGBA_color_model#RGBA8888) for more details. This got me and took me too long to realize since most of my images are black and white. My wrapper auto-coverts this to a more convenient format just like im2lib does

**Comment by TAAPArthur** [comment]
> Another thing. Can you tell if by using this lib, do I lose the ability (feature) to cache?

Forgot to answer this. Kinda. When all references to an image is closed, the underlying memory will be freed normally as far as the library is concerned. So if you try to open an already opened image, it is free. The exceptions are for stuff like remote images or pipes were we can't get the data once it is open and as such those live until the context is destroyed. Nothing is saved to disk and there's no predictive loading. However, if the underlying loader is Im2lib, then you'd be able to take advantage of the caching they do still. Honestly, don't know how helpful it is; loading the images and rendering them is fast for me without caching.

@explosion-mental If you have any more questions could you open an issue on my repo. I feel bad for talking about non-nsxiv stuff on the nsxiv repo.

**Comment by N-R-K** [comment]
> However, if the underlying loader is Im2lib, then you'd be able to take advantage of the caching they do still.

As far as I see, the imlib2_loader you're using uses `imlib_load_image_fd` to load an image, which doesn't use the cache.

**Comment by mamg22** [comment]
> I've never seen a --recompile flag!

@explosion-mental You might want to checkout too what Fedora's [`st-user`](https://src.fedoraproject.org/rpms/st/blob/rawhide/f/st-user) script does. You put your `config.h` and patches in a `~/.st/` directory, and everytime it detects a change, it will automatically apply patches and recompile `st` before launch.

**Comment by explosion-mental** [comment]
> @explosion-mental You might want to checkout too what Fedora's [`st-user`](https://src.fedoraproject.org/rpms/st/blob/rawhide/f/st-user) script does. You put your `config.h` and patches in a `~/.st/` directory, and everytime it detects a change, it will automatically apply patches and recompile `st` before launch.

and

> `--recompile` was inspired from xmonad which behaves the same way.

Interesting, I do prefer to `make install` than `--recompile` but I see the convenience.

_I've only used i3 for like 30 mins only to install dwm, too comfy (and lazy) to try other wms_
