### ISSUE TITLE
IPC support

### ISSUE THREAD

**Issue by duarm** [nsxiv/nsxiv#208]
Hello! 
IPC was discussed and considered on  #108 , I'm here to make a formal request for this feature, do you guys still plan to add it?

My primary use case, aside from controlling nsxiv remotely (I can already hack this feature with xdotool), would be to load images to nsxiv without writing to disk (and relying on inotify). My motivation is to use nsxiv as a decoupled image viewer for an image downloader, so some specific features like manual redraws would be nice, we can discuss the design if anyone is willing to help me with this.

Thanks for supporting sxiv!

**Comment by N-R-K** [comment]
> would be to load images to nsxiv without writing to disk

Hi, I don't think IPC would solve your problem. (n)sxiv uses Imlib2 for loading images and Imlib2 doesn't have any way to load images from memory. It's the same reason why we couldn't implement pipe support discussed in #32

> My motivation is to use nsxiv as a decoupled image viewer for an image downloader

I'm not entirely sure what this means.

> so some specific features like manual redraws would be nice

I assume you should be able to do something like this to force a manual redraw via keybinding:

```diff
diff --git a/config.def.h b/config.def.h
index 0973ff4..c8d8884 100644
--- a/config.def.h
+++ b/config.def.h
@@ -89,9 +89,13 @@ static const unsigned int USED_MODMASK = ShiftMask | ControlMask | Mod1Mask;
 /* abort the keyhandler */
 static const KeySym KEYHANDLER_ABORT = XK_Escape;
 
+bool manual_redraw(arg_t _) { return true; }
+#define g_manual_redraw { manual_redraw, MODE_ALL }
+
 /* keyboard mappings for image and thumbnail mode: */
 static const keymap_t keys[] = {
 	/* modifiers    key               function              argument */
+	{ ControlMask,  XK_r,             g_manual_redraw,      0 },
 	{ 0,            XK_q,             g_quit,               0 },
```

**Comment by duarm** [comment]
> I'm not entirely sure what this means.
imagine sending the downloaded images to sxiv instead of having my own image renderer/lib

> Imlib2 doesn't have any way to load images from memory
that's unfortunate, but even so, I think there's value in implementing IPC just for the remote communication, and having everything already set up for the day imlib add this feature.

**Comment by N-R-K** [comment]
> imagine searching for images and having them being previewed in nsxiv instead of having my own image renderer/lib

Tbh, I'm still not entirely sure what you mean. But I'm assuming you're trying to use nsxiv as an image previewer? If so then there's two ways you can do so.
1. Do what [preview-tabbed](https://github.com/jarun/nnn/blob/master/plugins/preview-tabbed) is doing by using [tabbed](https://tools.suckless.org/tabbed/) as a dummy/parent window.
2. Use the Linux inotify feature (nsxiv should compile with it enabled by default)
```console
$ cp ~/pictures/img1.png /tmp/tmp.png
$ nsxiv /tmp/tmp.png &
$ cp ~/pictures/img2.png /tmp/tmp.png
```
Assuming you're using `/tmp` as a ramdisk, then you can technically avoid writing to disk this way as well.

**Comment by duarm** [comment]
yeah, the tmpfs was my last resort, I figured just sending the images to nsxiv would be easier. thanks for the help with my use case, should I close this or IPC is still being considered?

**Comment by N-R-K** [comment]
We can keep it open. Some of my thoughts on the IPC implementation if someone wants to pick it up:

1. It must be portable, preferably using POSIX interface, but X is fine too since we depend on it.
2. Should ideally be 2 way and easy to interact with via scripts.
2. Ideally the code should be mostly isolated and thus could be easily disabled via `#ifdef` guards for those who may not want it.

**Comment by N-R-K** [comment]
Also reposting one of my concerns from the earlier thread; while a generic IPC is appealing, I'm not entirely convinced it's needed either and might just be overkill:

https://github.com/nsxiv/nsxiv/issues/108#issuecomment-934355961
> The only things that cannot be done via keybindings are adding/reordering/resorting the current images.
> But if those really are the only usecases, then maybe we should look into adding those features into nsxiv rather than generic IPC which would be overkill for this purpose.

**Comment by 0ion9** [comment]
@N-R-K 
* reordering is not especially hard to implement ( and I find it so indispensable that obviously I'd prefer it to be in nsxiv)
* Resorting IMO can be done through clipboard + restarting nsxiv, if you're willing to clobber clipboard and also any marks you might have set. If not, then maybe IPC. But maybe just having some way to selectively tell sxiv 'send whole filelist to keyhandler, not selected images' would address both this and 'get current filelist' (mentioned in #108). Prefix key, maybe. You'd still lose state like marks and zoom mode
* Adding or inserting images (or removing per a criteria). don't see how to avoid IPC here- I think restarting is less reasonable in these cases. It would be really nice if the keyhandler could return something indicating 'add/ remove IMAGE after REF' where REF can be an index in [-1..nfiles] and/or the path to an image. Both might be needed since in some cases multiple references to same path could exist in a filelist. That would of course have the same requirement that the keyhandler could somehow receive entire filelist not just selected files. I feel like there would be an issue for that, but I don't have time to check right now.

* What else.. synthetic key events (`xdotool key` etc) *can* work to trigger a lot of in-nsxiv actions, but they can get pretty janky if the action tries to interact with the user, or there is a timing element. A little ugly, but I favor this over generic IPC for most 'synthetic' actions.

**Comment by N-R-K** [comment]
> Adding or inserting images (or removing per a criteria). don't see how to avoid IPC here

Removing can be done manually via <kbd>D</kbd> , not exactly sure if removing depending on some arbitrary criteria is a common enough usecase to bother with.

Regarding the adding part, see: #210

**Comment by N-R-K** [comment]
#255 and #256 made me think that if we implement IPC, then people might want to listen for certain events as well. So for example:

```console
$ nsxiv-ipc --listen "filechange" && do_stuff_when_file_changes
```

would block until a "filechange" event has been generated.

The idea seems cool, but I don't think it's going to be easy to implement given that sxiv code wasn't designed for it to be extended in ways like this. Muennich has even stated multiple times in the past that he would've went with embedding lua if he wanted sxiv to be highly scriptable.

---

I guess what I'm more or less trying to say here is that a generic IPC may not be something that fits nsxiv, even though I do see some usefulness of such a feature.

**Comment by duarm** [comment]
the problem is that this can't be achieved with in a stable way with patching, as you said, sxiv wasn't designed for this, I would expect the patch to break a lot. Only a fork would do then?

I completely understand your position tho, a shame there's no other image viewer as scriptable as nsxiv, even when it's not fully commited to it.

**Comment by N-R-K** [comment]
> Only a fork would do then?

Depends on how hardcore you want to go. For example, I think bspwm does *everything* including keybindings via IPC.

So if you want to fully commit on it, then I think it's probably going to be easier to just rewrite the nsxiv's core architecture from scratch with IPC in mind rather than trying to modify/fork the existing code.

But in any case, querying for the current image can be hacked around with `image-info` as shown here: https://github.com/nsxiv/nsxiv/issues/255#issuecomment-1095088906

So the only thing remaining so far which cannot be done is modifying the existing files on a running nsxiv instance. And I guess that's better done via `filelist-filter` as proposed in #210 rather than generic IPC.

---

In any case, I'll keep this issue open for a bit longer to see if someone else has anything interesting to say.
