### ISSUE TITLE
"BadLength (poly request too large or internal Xlib length error)" when viewing files with emoji in their names

### ISSUE THREAD

**Issue by rpdelaney** [nsxiv/nsxiv#227]
```console
$ nsxiv -v
nsxiv 28
$ nsxiv "🥰.jpg"
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  678
  Current serial number in output stream:  694
$ cp "🥰.jpg" "foo.jpg" && nsxiv foo.jpg
'🥰.jpg' -> 'foo.jpg'
$
```

**Comment by explosion-mental** [comment]
likely because it can't render the emoji in the status bar (displaying the filename)

**Comment by explosion-mental** [comment]
Yep, I have tested with vanilla `nsxiv` and works fine. You need [libxft-bgra](https://github.com/uditkarode/libxft-bgra) for xft emoji support.

**Comment by mamg22** [comment]
Can reproduce. This is an issue on pretty much every program that attempts to draw color emoji with Xft (such as `st` or `dmenu`). There's the libxft-bgra suggested above, and a few workarounds if you can't/don't want to get libxft-bgra, such as removing or disabling color emoji fonts, or making the program reject color fonts.

I've made a small patch based off current master that rejects color fonts, which seems to work fine (change the extension to `.diff` and apply):

[nsxiv-reject-color-fonts-ad95012.txt](https://github.com/nsxiv/nsxiv/files/8113783/nsxiv-reject-color-fonts-ad95012.txt)

**Comment by rpdelaney** [comment]
Thanks for the context. I am using `dmenu`. Arguably, there is still something to be desired in the UX here since the error message is not very helpful for explaining the problem. Is this something nsxiv could handle more gracefully, or should I raise this with the `dmenu` team?

**Comment by N-R-K** [comment]
> Is this something nsxiv could handle more gracefully, or should I raise this with the `dmenu` team?

This problem is with `libXft`, it's not under dmenu's control. There's a merge request fixing it open for 2 years it seems https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/1 , not sure what the status is or if they even plan on fixing the issue or not.

Anyhow dmenu (and other suckless softwares) simply works around it like this https://git.suckless.org/dmenu/file/drw.c.html#l136

---

I'm not sure if we want to add such workaround on nsxiv or not. Because then it'll mean users who are using `libxft-bgra` will need to patch nsxiv in order to use emojies.
I'm fine leaving it as is and instructing users who want to deal with emojies to install `libxft-bgra` instead, though no strong opinion on it, since it just trades one problem for another either ways.

**Comment by N-R-K** [comment]
On second thought, people using `libXft-bgra` should already be familiar with patching out workarounds since most suckless softwares have workarounds in place.

---

@XPhyro @eylles Thoughts on this?

**Comment by XPhyro** [comment]
I'd opt for not having a workaround in nsxiv.

suckless software like dmenu, dwm (status bar), etc. deal with text. We only show the filename. I don't imagine it begin common to have filenames, and it's less devastating if nsxiv crashes, say as opposed to dwm.

If one has emojis as filenames, they should use or probably already use libxft-bgra. There's no end if we start putting in workarounds for niche things that are not even caused by nsxiv.

**Comment by eylles** [comment]
I also opt for not working around it, also add to the readme that anyone who doesn't want to deal with vompiling libxft-bgra should go and comment on the libxft request, they have been delaying it for no good reasons for a long time already, the more pressure the xorg devs have to merge bgra the better in my opinion.

**Comment by explosion-mental** [comment]
> add to the readme that anyone who doesn't want to deal with compiling libxft-bgra should go and comment on the libxft request
That's a nice idea, maybe adding `image with an emoji on it crashes nsxiv` to the FAQs.

**Comment by rpdelaney** [comment]
> maybe adding image with an emoji on it crashes nsxiv to the FAQs.

That would have helped me, for what it's worth :o)
