### ISSUE TITLE
Preparing for release.

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#24]
~~Once https://github.com/nsxiv/nsxiv/pull/15, https://github.com/nsxiv/nsxiv/pull/31, https://github.com/nsxiv/nsxiv/pull/23 and (depending on if we agree to accept the configure script) https://github.com/nsxiv/nsxiv/pull/19 is merged, I think we should~~

- [x] proceed with rename https://github.com/nsxiv/nsxiv/pull/9
- [x] get a new icon https://github.com/nsxiv/nsxiv/issues/26
- [x] document new changes in changelog
- [x] add a project scope and contribution guideline https://github.com/nsxiv/nsxiv/discussions/39
- [x] add [nsxiv-rifle](https://github.com/nsxiv/nsxiv/wiki/nsxiv-rifle) to the wiki
- [x] add F.A.Q section on README
- [x] change Xresources `.font` to `.bar.font` for consistency https://github.com/nsxiv/nsxiv/pull/48
- [X] cleanup the documentations https://github.com/nsxiv/nsxiv/pull/60
- [X] add .mark.foreground to Xresources https://github.com/nsxiv/nsxiv/pull/51
- [X] cleanup config.h https://github.com/nsxiv/nsxiv/pull/61
- [X] tag a new version, add link to it in CHANGELOG.

The animated webp patch will need _massive_ refactoring, so there's no point in waiting for that.

One more patch I'd like to look into is the dmenu like picker https://github.com/muennich/sxiv/pull/405
However at it's current state it doesn't work on multiple files, so I'll need to rework this as well.

Is there any other small and sensible patches that can be added before a release?

**Comment by eylles** [comment]
i think it is worth to run some tests to determine how necessary is @0ion9 's https://github.com/0ion9/sxiv/commit/6ae2df6ed549c2cc119bd7d235b75154fc042d2d fix to the potential problem reported [here](https://github.com/muennich/sxiv/issues/391) that happens when rewriting large images, i can't replicate the bug as my current hardware is rather on the beefy side and i rarely do write large images while running other resource intensive tasks on the side.

in terms of "small" patches there's [this](https://github.com/mohkale/sxiv/commit/5de527a894138ec370912a558e1115a62dcac492) one that adds a new flag to set the initial size of thumbnails, not sure if the usecase justifies it as the initial thumbnail size can also be set on the config.h file before compilation.

on the camp of pure issues i think ti would be worth taking a look at issue [#433](https://github.com/muennich/sxiv/issues/433) and [#412](https://github.com/muennich/sxiv/issues/412) which seems to me as cases of bad metadata, altho those can also be comfotably looked on after the first release.

on track with discussin the first release of nsxiv, do we continue where muennich left and release v27, start anew with this release tag being nsxiv v1, or go back into using a semantic versioning with this being perhaps nsxiv v1.0.0 ?

**Comment by N-R-K** [comment]
We should start looking at the open issues, good call.

As for versioning, I'm fine with both.

**Comment by GRFreire** [comment]
About versioning, i think we should go with the first option (v27). Start from v1.0.0 would only make sense (imo) if nsxiv was a rewrite of sxiv.

**Comment by eylles** [comment]
we could always say this is v27.0.0 if it comes to that

**Comment by N-R-K** [comment]
> bump the number after the `.` every time a big fix is merged

That's unnecessary, most distros package stable releases. We should only bump tag on new release.

Also I think a lot of package manager might be using RSS to get notification on new release. If we spam tags that just spams their feed.

**Comment by eylles** [comment]
i will start runing some tests with a compiled dev HEAD to see if i can narrow down the possible causes for [#412](https://github.com/muennich/sxiv/issues/412) and [#433](https://github.com/muennich/sxiv/issues/433) altho a comment in 412 makes the implication that it is a imlib2 problem i doubt it as the problem arises with animated gifs, which makes me think it may be a problem with giflib. I must add it is bothersome neither comments bothered mention which distro this error was encountered in nor the exact version of imlib2 or libgif.

**Comment by XPhyro** [comment]
We should also write up a wiki entry about packaging nsxiv and explain nuisances in #15, #19, etc. We can then reference this entry in the readme.

**Comment by eylles** [comment]
> 
> One more patch I'd like to look into is the dmenu like picker [muennich/sxiv#405](https://github.com/muennich/sxiv/pull/405)
> However at it's current state it doesn't work on multiple files, so I'll need to rework this as well.

@explosion-mental can you help with the dmenu patch for this behaviour?

**Comment by N-R-K** [comment]
There's a couple more problems with it. `dmenu` will insta print out when you make a selection via <kbd>ctrl+enter</kbd>, we'll have to decide if we want to mimic that or not. Overall, that patch involves some more design decisions so I think we can leave it out of the initial release.

**Comment by eylles** [comment]
yeh, i could open a Draft PR with the original patch rebased on dev HEAD, we can have it there for consideration and working what the proper behaviors should be and work on it slowly, if it somehow manages to be ready before first release good, if not rebase on master post-release and we work on it, what do you think?

**Comment by N-R-K** [comment]
I think the original patch is a bit short-sighted since it didn't even consider multiple marks. I'll get something more robust and open a PR on a cleaner base.

**Comment by N-R-K** [comment]
@XPhyro don't tag yet. one more thing needs to be done.

**Comment by XPhyro** [comment]
The original comment is done, what is it?

**Comment by N-R-K** [comment]
We need to change the enum's in config.def to const ints. and the bump version should also bump CHANGELOG. I'll get to it.

**Comment by N-R-K** [comment]
`v27` is released. :tada:
