### ISSUE TITLE
Event reporting

### ISSUE THREAD

**Issue by anon00000000** [nsxiv/nsxiv#256]
Hello, I'd like to use a mainline sxiv (excluding config, of course) to replace my patch at https://git.sr.ht/~q3cpma/sxiv-manga-reader including those features:
* Quitting when trying to go past/before the last/first image: would adding a new `i_navigate` variant be okay?
* Reporting the exit reason and position: either a limited option or a more general event reporting mechanism? I don't think modifying the commands in the right way to go, here.

**Comment by N-R-K** [comment]
> my point is that it would make sense to be included, even outside my usecase.

Could you give some examples? If it's something that's going to be commonly used, then we can include it in mainline. But otherwise, you'll unfortunately have to content with a custom function.

> I mainly want to differentiate between "quit because nav_quit() exited" or "quit because quit() was called or WM_DELETE_WINDOW was caught".

On your custom function you can either exit with a different status or maybe print something to stdout/err.

>  In the end, since configuration is done a build time, I still need two sxiv binaries =(.

You can check out div from the "related projects" section in the README. I *think* it allows you to do your configuration with a shared library (?). So you'll only have to recompile your config upon changes.

ping @TAAPArthur

**Comment by q3cpma** [comment]
> Could you give some examples? If it's something that's going to be commonly used, then we can include it in mainline. But otherwise, you'll unfortunately have to content with a custom function.

Not really, I just find the current behaviour as arbitrary as quitting, but understandable since you don't want to quit by mistake. 

> On your custom function you can either exit with a different status or maybe print something to stdout/err.

I did, but I still had to patch `commands.c`, which made me realize what uncontroversial change would really improve nsxiv here: transforming the [event switch](https://github.com/nsxiv/nsxiv/blob/master/main.c#L778) into a `config.h` mapping like the other events (keyboard/mouse being just another type of event).
The beauty of the thing is that it'd "solve" my event request: I could just wrap every function in here. The downsides is that it requires wrapping the current switch cases into 6 new (albeit small) functions just to achieve that and that'd make nsxiv even more of a Greenspun's 10th rule contraption.

**Comment by N-R-K** [comment]
> transforming the [X event switch](https://github.com/nsxiv/nsxiv/blob/master/main.c#L778) into a config.h mapping like the other events

Not entirely sure what you have in mind. But if you're thinking about doing something [similar to DWM](https://git.suckless.org/dwm/file/dwm.c.html#l247), then this is something I've thought about in the past but didn't like it at the end.

Unlike dwm, we don't handle many events, only 6. Also I don't think we're listening for all X Events either (?), so it can mislead people into thinking they can write a handler for any arbitrary X Event when that's not the case.

I guess instead of having an array of all possible X events, an alternative can be having function pointers only for the events we're handling.

Though, introducing function pointers into config.h is kind of messy. It opens up questions about what deserves a function pointer and what doesn't, because I'm sure everyone can come up with at least one usecase for wanting a func ptr for pretty much everything.

**Comment by TAAPArthur** [comment]
>You can check out div from the "related projects" section in the README. I think it allows you to do your configuration with a shared library (?). So you'll only have to recompile your config upon changes.

Giving the user flexibility to do whatever they want was a driving point of div (and it was made to be a manga reader). It isn't impossible to add that flexibility to nsxiv but it would be a rewrite/restructuring that wouldn't get approved. 
I agree with @N-R-K that a custom function is your best bet. Auto quiting on page end if useful in certain situations. I don't think a generic image viewer is one of them. Even for manga reading, quitting isn't exactly ideal behavior when reaching the end of a page when you can't easily go back to the previous one.

>Not exactly, I mainly want to differentiate between "quit because nav_quit() exited" or "quit because quit() was called or WM_DELETE_WINDOW was caught".

I think we could support this. Perhaps we should exit 0 if the user called nav_quit (ie the user explicitly chose to exit), exit N on some unrecoverable error (X errors, crashes, OOM etc) and maybe exit M for when the WM asks the window to die. Then you could tell "why" the program quit. We also talked about having general [session support](https://github.com/nsxiv/nsxiv/issues/215.

**Comment by N-R-K** [comment]
> maybe exit M for when the WM asks the window to die.

If the WM is telling us to die, it's most likely coming from the user. It's not uncommon to quit via the WM hotkey instead of in app quit key.

I'm not sure if exiting with a non zero status is a good idea on such cases.

**Comment by q3cpma** [comment]
On Sun, Apr 17, 2022 at 11:29:02PM -0700, N-R-K wrote:
> > maybe exit M for when the WM asks the window to die.
>
> If the WM is telling us to die, it's most likely coming from the user. It's not uncommon to quit via the WM hotkey instead of in app quit key.
>
> I'm not sure if exiting with a non zero status is a good idea on such cases.
>
Indeed, non zero exit status should be reserved for errors. All considered, I'm
relatively happy with the current state of things, the only way to cleanly
improve sxiv on that front would be a redesign (something à la imv, perhaps).

**Comment by TAAPArthur** [comment]
>If the WM is telling us to die, it's most likely coming from the user. It's not uncommon to quit via the WM hotkey instead of in app quit key.

Guess it depends on the workflow WM and don't know what is "normal". In my workflow closing with the WM involves killing the X connection of the client (which is different than WM_DELETE_WINDOW and the DestroyNotifyEvent) which generally results in a non-zero exit status. And I use that to differentiate from a normal shutdown (ie via pressing the quit key). Perhaps it is arbitrary but it'll work for every application I've tried although other WMs may kill differently. The general idea is that you have 2 hot keys for normal and non normal exists and you script around it. (For the context of a manga viewer, success means mark read for me.)

Having a macro/global var in config.h for the default error and WM exit status would allow for such flexibility. I don't have a strong opinion, but just putting that out there. As an aside WM_DELETE_WINDOW and DestroyNotifyEvent should probably result in the same exit status.

**Comment by N-R-K** [comment]
> the only way to cleanly improve sxiv on that front would be a redesign

Correct. While sxiv is flexible enough, it wasn't designed to be. Trying to be fully flexible would require either going full-blown IPC similar to bspwm or embedding lua similar to AwesomeWM.

Given our project scope, neither is likely to happen.

**Comment by TAAPArthur** [comment]
>@TAAPArthur What's the ICCM/EWMW stance on this? If they have guideline related to it, then makes sense to follow that.

As far as I'm aware the spec doesn't outline anything as specific as exit statuses.
Out of the ways to kill a window

- XKillClient - X connection is forcibly closed. The same as the Xserver dying or receiving an unrecoverable error from the client perspective and 
- DestroyNotify - Someone send a request to kill the window manually. According to the ICCCM spec, this shouldn't happen via a WM for nsix
```
 If the client aborts a destroy and the user then selects DELETE WINDOW again, the window manager should start the WM_DELETE_WINDOW protocol again. Window managers should not use DestroyWindow requests on a window that has WM_DELETE_WINDOW in its WM_PROTOCOLS property. 
 ```
 - WM_DELETE_WINDOW - WM should ask nsxiv to close the window but not necessarily exit
- _NET_CLOSE_WINDOW - This seems open to interpretation
```
 Pagers wanting to close a window MUST send a _NET_CLOSE_WINDOW client message request to the root window: 
 The Window Manager MUST then attempt to close the window specified. See [the section called “Source indication in requests”](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#sourceindication) for details on the source indication.

Rationale: A Window Manager might be more clever than the usual method (send WM_DELETE message if the protocol is selected, XKillClient otherwise). It might introduce a timeout, for example. Instead of duplicating the code, the Window Manager can easily do the job.
```
I'm pretty sure most WM will follow what is suggested by by the rationale but technically it leaves it open to interpretation.

I believe my point in 54 was that the the nsxiv window dies for whatever reason, we should exit instead of just wasting resources. In my opinion all of these should result in the same non-zero exit status and we should only exit normally if nsix itself choose to exit. But this is coming form someone who doesn't have widow decorations like the giant x button to close a window which may be the normal way of exiting for some.

I don't have a strong opinion as anyone who really cared could make the 1 character change themselves and we could easily make it configurable should the need ever actually arise.

**Comment by N-R-K** [comment]
> In my opinion all of these should result in the same non-zero exit status and we should only exit normally if nsix itself choose to exit. But this is coming form someone who doesn't have widow decorations like the giant x button to close a window which may be the normal way of exiting for some.

Even without decoration, exiting nsxiv via WM keybinding is probably common thing I'd assume. So I don't think we should change that to non-zero. Changing `DestroyNotify` to zero seems OK to me unless there's some reason not to.
