### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#26]
Since we're renaming, I think we'll need a new icon for release.
Do we go for a brand new icon, or just add `N` in front of the current one?

**Comment by XPhyro** [comment]
I think an `n` suffices, but I'll not object to the other option.

By the way, #9 includes this icon which is currently the avatar of this organization:

![avatar](https://avatars.githubusercontent.com/u/90395597)

**Comment by N-R-K** [comment]
Looks fine to me. What about embedding the icon in `icon/data.h`?

**Comment by XPhyro** [comment]
We gave it a go with @eylles, but could not. See the discussion in #1.

Feel free to try it out.

**Comment by eylles** [comment]
We have the problem of not knowing exactly how muennich did the compression of the original icons, i looked around but the best i got is that itis somehow a NES dtyle compression, but doesn't match it exactly as the generated palette has only 10 colors.

To which we have 2 options:
 1) schew compression entirely and modify the code that handles the icons so it can handle uncompressed headerless icons.
 2) use xseticon, either direcrly or add it's source code into the nsxiv codebase.

**Comment by N-R-K** [comment]
Maybe we just leave it in as easter egg :^)

**Comment by eylles** [comment]
I also asked around on how to modify the code that handles the embedded icon, i will put together a script to generate a new data.h and test the suggested modified code.

**Comment by eylles** [comment]
Thinking about the icon again, knowing that we have a 10 color palette, then probably the way the icon data arrays are built is a 2d array (a matrix) of values from 0 to 9 (i guess) and those determine which color of the palette gets asigned to each pixel, to be able to generate new icons then we should map which unique values within the pixel matrix correspond to which color (easier to do in the 16px icon), then knowing the values we have to figure out how the pixel data is written (a good idea may be looking at the code that handles it in window.c) as in, is the data written as conventional matrix:
| • | x0 | x1 | x2|
|----|----|----|----|
|y0|0|1|2|
|y1|1|2|3|
|y2|2|3|4|

Or does it have a vertical flip?
| • | x0 | x1 | x2|
|----|----|----|----|
|y2|2|3|4|
|y1|1|2|3|
|y0|0|1|2|

after we know how it is ordered then we can proceed and generate the data for the new icons in a way similar to converting images to ascii art, but instead of simply having ascii caracters to represent each pixel we put a number from 0 to 9, then we can sed that data into the proper array format for example `sed 's/0/0x00/'`.

What you think?

**Comment by XPhyro** [comment]
The new icon is in place. Resolving the `data.h` issue should have its own issue.

See #104.
