### ISSUE TITLE
Rethinking config.h

### ISSUE THREAD

**Issue by TAAPArthur** [nsxiv/nsxiv#36]
Summary: Basically want config.h to contain only *changes* to the default behavior such that if something isn't specified in config.h, I get the default behavior.

So it seems to be that our personal config files are very fragile. If we add a new option to config.def.h that is used somewhere, then any config.h that was created beforehand will no longer compile. I think that by all our options should have a default value and config.h should be able to include only the minimal amount of changes a user wants. I believe we can achieve this with weak refs.

Minimal Proposal
1. Include config.def.h instead of config.h in all but one file. Have config.def.h include config.h
2. Replace all the `static` modifiers with weak refs in config.def.h
2. Don't auto generate config.h from config.def.h. It could just be an empty file by default.

Note this is just the minimal set of changes to get the benefits proposed. Some files should probably be renamed.
 
Pros:
- config.h is forwards compatible against new features
- Changes made to a config variable will be visible across different files. I know everything is const now, but that just seems like a gotcha down the road.

Neutral:
- Changes to keybindings won't benefit from this. New keybindings will have to be manually added to the config.h if config.h already has custom keybindings. Could workaround this with an user_keybindings array or something that will overwrite any keybinding found in the defaults or something 

Cons:
- Think the removal of static will break all existing configs, but simply blindly removing `static` everywhere should resolve this.

Alternative:
Instead of this approach, one could store their customization to config.h as a patch and just reapply the patch on update. No comment on how well this work in practice

And while we are here, any objection to removing all the ifdefs in config.def.h?

Thoughts?

**Comment by XPhyro** [comment]
I'm neutral towards such a rework, but, if we are to rework `config.h`, I think we can just `#include "config.def.h"` in the beginning of `config.h`, and overwrite the included values. This would probably be a cleaner way to go about a config refactoring.

**Comment by N-R-K** [comment]
`config.def.h` and `config.h` is pretty standard way for dealing with compile time configuration on suckless style software. If we deviate, it just causes needless confusion towards users that are already familiar with suckless style software.

It's a negative from me. 👎

**Comment by N-R-K** [comment]
> And while we are here, any objection to removing all the ifdefs in config.def.h?

I'm not sure why it's there to begin with, I haven't seen such on any other suckless software either. Maybe muennich just wanted a cleaner namespace by only loading the chunk that's needed? Maybe lower compile time (doubt it) ?

I'm not against deviating, ***if theres tangible benefit to be had.*** I'm not really seeing any benefit. So I'd say lets stay consistent with the current style.

**Comment by eylles** [comment]
> I'm neutral towards such a rework, but, if we are to rework `config.h`, I think we can just `#include "config.def.h"` in the beginning of `config.h`, and overwrite the included values. This would probably be a cleaner way to go about a config refactoring.

I like this idea for config.h generation, as with the cases described config.h is a bit clunky as of now, if you patch in something that changes config.def.h those changes won't go into config.h unless you re-generate it or add them manually, if you have personal prefferences set in config.h constantly re-generating it isn't ideal, if the changes an applied patch adds then manually adding them isn't ideal either, so a method to have the defaults of condif.def.h always be present in config.h without re-generating it unless you are explictly overwriting them, however this adds a new problem, which is if you want to remove something that the default sets, let's say you want to completely remove mouse operation from your sxiv config.h in this hypotetical config.h that includes config.def.h, you can't simply not add mouse mappings, as the `#include "config.def.h"` will simply add them back, you would have to write the mouse mappings but assign them no function nor argument.

I see this being more tricky than it seems at first glance.

**Comment by eylles** [comment]
Giving it another tought, making such large changes to config.h has more detriments than value, binary distro users would get no benefit from it whatsoever, for source distro users (or those that want custom builds) it would make things confusing by not following the same model as similar programs like suckless tools.

At this point allowing to fully configure keybinds and other default values from within xresources would have more value as at least binary distro users would get something out of it.

**Comment by XPhyro** [comment]
> however this adds a new problem, which is if you want to remove something that the default sets...

That's a good point, I didn't think about it.

**Comment by TAAPArthur** [comment]
>> however this adds a new problem, which is if you want to remove something that the default sets...

> That's a good point, I didn't think about it.

You can still clear it out depending on how it is done.
If we have user configs in a config.c, then in config.c
```
const button_t buttons[] = {0};
```
And this would override the defaults and make buttons a array with a single invalid element. This wouldn't work if by definitions were in the same translation unit at least not with gcc.

And this leads to something I dislike about `config.h` in that we abuse header files. They kinda work for projects with a single source just so you can't compile a single program. In our case, the config.c seems more sane. Also allows for users to write their own functions in the config file without having to `static inline` all of them

If you want a minimal sample to test out, test.c:
```
#include <stdio.h>
int buttons[4]  __attribute__((weak)) = {1,2,3};
int main() {
    printf("%d\n\n", sizeof(buttons));
    printf("'%d'\n", buttons[0]);
}
```
and test2.c
```
int buttons[]   = {0};
```
And compiling with `gcc test.c test2.c && ./a.out`

**Comment by N-R-K** [comment]
> If we add a new option to config.def.h that is used somewhere, then any config.h that was created beforehand will no longer compile.

Put this in `.bashrc` and this should no longer be an issue.
```sh
mk() {
  case "$PWD" in
    path/to/nsxiv*) rm config.h && make "$@" ;;
    *) make "$@" ;;
  esac
}
```

As I've already stated, I'm **strongly** against this because it breaks a well established convention.

**Comment by GRFreire** [comment]
> And while we are here, any objection to removing all the ifdefs in config.def.h?

None, I actually think its the right move to do so.

> As I've already stated, I'm strongly against this because it breaks a well established convention.

I have to agree here with @N-R-K , everybody that ever touched a `config.h` file will be confused.

**Comment by TAAPArthur** [comment]
>Put this in .bashrc and this should no longer be an issue.

Uh I don't understand what the code section is intended to do. I get running `mk` would delete config.h, I don't see why that should ever be done. Presumably there are some user settings there that they don't want deleted and if they did they could do it themselves. 

>As I've already stated, I'm strongly against this because it breaks a well established convention.

Not all suckless-like programs follow the conventions of having a config.h. xmonand is a great example. Also one could argue that the suckless convention would be to put everything into one file which I think would be better than multiple files including a config.h

**Comment by N-R-K** [comment]
> I don't see why that should ever be done.

So that it forces copying the new `config.def.h`, isn't that the entire point here?
As for users, binary users get nothing out of this and users who are trying to compile it themselves will just get confused because we're completely deviating from the norm.

**Comment by TAAPArthur** [comment]
@GRFreire Could you elaborate on what exactly you are against. Right now everyone who has a custom config.h will have to update it to build with the latest source. Are you against this being an issue, changing all the static modifiers to weak refs or just changing the relationship between config.h and config.def.h?

I'm not seeing a downside to say including both config.def.h and having config.h override it. If you want to specify everything yourself you still can.

>So that it forces copying the new config.def.h and the program builds properly. Isn't that the entire point of this issue?

The point was how to seamlessly integrate new config options with future configs. Like intentionally paying a fixed cost of switching manually updating their configs but then never having to again unless they want to change behavior. It wasn't about forcibly deleting user configs just to get the program to build. 

>As for users, binary users get nothing out of this and users who are trying to compile it themselves will just get confused because we're completely deviating from the norm.

Yes binary users don't benefit but they don't hurt either. As for everyone else, they have to change their config regardless. Keeping config.h isn't off the table.

**Comment by TAAPArthur** [comment]
@GRFreire @N-R-K 
Just to make sure we are talking specifically about the same thing, what step of the following proposal do you "strongly" object with?
 
1. Replace all config.h includes with config.def.h. 
2. Split config.def.h into a header with the declarations and a source file with definitions (config.def.c).
3. Replace the static modifiers with weak refs. 
4. Have a config.c that includes config.h. (Could just be a simply contain `#include "config.h"`
5. Link config.c and config.def.c with everything

We can keep the default config.h (the one generated from config.def.h) as an exact copy or make it an empty file.
We also don't strictly need config.c. Believe some compilers will let you pass in config.h directly (and treat it as the default config.c proposed above), but imagine that is less portable.

Some cons to this approach
- It does involve modifying existing config files. I'm justifying it has a one time modification to prevent future ones and a change that can be mindlessly done.
- And it does mean there's slightly more work of when adding a config option as 1 more file has to be touched.

But when you just say just you object to this because it is different, I don't find that helpful. I feel like its going to lead to an opinionated discussion about what the "norm" is as not all programs are the same and/or is the "norm" good for us. If I'm understanding your points correctly and you just want to keep a config.h, there are ways to do that. And if I'm misunderstanding, please enlighten me. Like if you don't agree that the issue I'm trying to fix exists or have a better way to avoid it, that'd be good to know.

**Comment by GRFreire** [comment]
Let's see if I got it right:
- The problem that encouraged this issue is: "every time `config.def.h` changes, I need to regenerate my `config.h` and lose my custom configs".
- How to solve (simply putting): "make the `config.h` only have the custom options, all the others will fallback to default (`config.def.h`)"

My opinion on this:
I think that a simple `patch` could solve this. How? You generate `config.h` -> modify for your own needs -> generate a diff/patch file -> every time `config.def.h` changes, you just regenerate `config.h` and apply the patch.
A downside to this is that every time some option (that you have in your patch) is changed, it will no longer be able to patch automatically. But this will also need manual intervention if we follow the proposed solution, so not actually a downside (if we compare them).

Since both of these solutions solve the problem, the downside of the `patch` one is also present in the proposed one, and the last have will change both how we configure stuff in nsxiv and also the codebase, i think we should stick with the default.
 
Idk if I made myself clear now, feel free to ask (or correct) me again if needed.

**Comment by N-R-K** [comment]
> Just to make sure we are talking specifically about the same thing, what step of the following proposal do you "strongly" object with?

Pretty much all of it. I think we're trying to solve a problem that doesn't really exist.

[Users are encouraged](http://dwm.suckless.org/customisation/patches_in_git/) to use git to keep track of their builds. So if that's what someone is doing, and a new change has been made, he can just see it in the git log. It's a non issue.
And if someone isn't using git (may god help them) adding new things in `config.def.h` breaking build is a **good** thing because it tells them they need to update their config.

And as I've already said, `config.def.h` and `config.h` have a conventional behavior. [It's been 11 years](https://bbs.archlinux.org/viewtopic.php?id=112643) since sxiv was born, it's a mature software with a mature codebase. We shouldn't just throw things away, especially trying to solve a non-problem. There are far more important problems (like extensionless gif files not loading) that have real impact and needs solving.

> You generate `config.h` -> modify for your own needs -> generate a diff/patch file -> every time `config.def.h` changes, you just regenerate `config.h` and apply the patch.

Or you keep track with git, make your changes directly in `config.def.h` and rebase on new commits. We shouldn't treat the user base, especially those who are compiling from source as incompetent users and try to set default behind their back for them.

**Comment by eylles** [comment]
And as i've said, for the reduced long term benefits that this may bring something more beneficial would be to have full configuration through xresources or a dedicated config file (i'm not suggesting we add this to nsxiv) as at least then binary distro users get some benefit.

**Comment by TAAPArthur** [comment]
@GRFreire I understand your point. I agree with your thoughts on patching. I was just hoping for a system more robust against conflicts.
> But this will also need manual intervention if we follow the proposed solution, so not actually a downside (if we compare them).

I don't believe this is true. Unless the signature changes to something incompatible, the custom config won't need to be changed ever. Even if the option is removed, the config file will still functions. Additionally we won't have to modify it if a new config option is added near it. The goal is to have config.h be forwards compatible and therefore never has to be updated unless the user wants to change a default.

@N-R-K So the new feature adding support to have file name in the window title should break by build? What benefit does this bring

So this is a problem to me and my setup can benefit from it unlike the gif issue. We aren't all going to have the same problems. My use case is similar to that of a package manager who just wants to be able to up the version number for new releases (and maybe the release source) and not have to worry about the custom config breaking. In my case the config.h isn't kept in a fork of this repo for reasons. I don't think we need to make assumptions about how our users are going to build nsxiv especially when one of them (me) is implying something contradictory.

**Comment by N-R-K** [comment]
> What benefit does this bring

\>adding new things in config.def.h breaking build is a good thing because it tells them they need to update their config.

Explicitness over changing something behind the user's back. In this case for example, the title patch changes a default behavior from having "sxiv" as title to "sxiv - basename". We shouldn't just make this type of changes behind the user's back. If the build breaks, it tells them something changed and they can _consciously_ decide what they want to do with it.

> My use case is similar to that of a package manager who just wants to be able to up the version number for new releases (and maybe the release source) and not have to worry about the custom config breaking.

Most package managers deal with binary disros so it's a non issue. There's a handful of distros that allow for customizing your source. And as I've said, I don't want to set default behind those user's back.

Anyways, I'll take a break from this discussion now, and focus my energy elsewhere. In the meanwhile @kdkasad @bakkeby if you guys can give your opinion on this, that would be nice.

**Comment by N-R-K** [comment]
I can see why you guys don't get why I'm against this, I wasn't able to communicate my thoughts properly. So I'll try again:

- - -

> Don't auto generate config.h from config.def.h. It could just be an empty file by default.

So how will someone know what can be set in `config.h` if it's empty? They'll just have to go back and forth between `config.def.h` and `config.h` ? This does not sound good.


> Include config.def.h instead of config.h in all but one file. Have config.def.h include config.h

Slideshow delay and window dimension are declared as `enum` so users not can't re-declare or redefine them in `config.h`. So certain things can be redefined in `config.h` but not others? Does not sound like a good interface.

Also keybindings are an array of struct, so if someone wants to change _just one_ keybinding, he'll now need to copy the entire array over to `config.h`, this is madness.
Or he can try to be _smart_ and manually find the index of what he wants to change and in `config.h` do something silly like
```c
keys[16] = ..
```

And after a couple days, now he have no clue what `16` here means.

Also if we add new keybinding to default, then what `16` used reference is now no longer the same thing. So now we have magically changed one of the user's keybinding to something completely different. How can we justify that?

So to ""seamlessly"" integrate the changes proposed in this isssue, we have to:

* Rework how we handle keybindings _entirely_
* **Completely** throw away const correctness
* Pollute the namespaces. Something muennich actively worked against, evident from the `#ifdef` guards in `config.def.h`
* Confuse anyone that ever touched a suckless style configuration
* Add more complexity on the build system

All of this, just to do something that we shouldn't even be ***trying*** to do in the first place, manage the user's configuration for them. Can you see why I'm against this now?

**Comment by eylles** [comment]
After taking a look at many window mansgers and how user configuration is handled upon releases i think we should duplicate that approach, which is break existing configurations every major release (we already do) and make it clear on the release notes that existing configs will be broken detailing what changes did config.def.h (the default config) got since last release and telling users to rebase their oersonal config from the default.

Almost every big wm that is configured in a programming language does this, dwm, awesome, xmonad, spectrwm, dwl, bspwm, qtile
If the users are lucky the major version upgrade will be somewhat compatible, if not then it will outright crash until they load the default config and rework it from their previous config. 
If not even the window managers that have been on development for over 10 years have found a good and elegant way to not break user config on major version releases then there's no way we will find such magic code in a couple days.

**Comment by bakkeby** [comment]
This discussion does not have much value I feel.

`config.h` is a C header file, not a plain text configuration file, so you can't just source both and have the config.h settings override the other as you would be defining the same variable twice and compilation would fail. There is not much more to it.

You have to consider that these settings are read at _compile time_, not at _runtime_.

There are only a handful of existing patches that change configuration [[ref](https://github.com/bakkeby/sxiv-flexipatch/blob/master/config.def.h)]:
   - SVG image support
   - thumbs padding
   - dmenu-like behaviour
   - navigate if not scroll
   - scale fill mode and
   - allow escape key in external key handler

Beyond that you should not expect the configuration file to change that much or that frequently.

The `#ifdef`s  in the config file I believe are there so that when each module reads the configuration file it only reads the settings it needs rather than everything. The alternative would be to have a separate configuration headers for window.c, image.c, thumbs.c and mappings.c.

Dropping the `const` declarations from the configuration file will make it easier to override some settings via other means, e.g. via command line arguments or via xresources (the latter is not a particularly good idea imho).

If we want a "proper" configuration file then we should look into getting rid of the header files and add a configuration parser that does runtime validation etc. Maybe use lua or re-implement nsxiv in rust or python. All of this should hopefully be outside of the project scope (#39) :)

An alternative would be to just not have any configuration options.

Another alternative would be to rename `config.def.h` to `config.h`.  That way if someone does a git pull then they have to deal with any conflicts there and then. Of course here you need to take great care not to include your personal settings when committing a change to the default configuration.

Regardless of how you look at it there would be a lot of effort trying to work around that a few people might be confused when upgrading their version of nsxiv while keeping their old config.h file.

It is the way it is because it follows the same principle that other suckless tools follow. That is not to say that this is the right, or best, way to handle configuration.

There are of course silly things in there that should be made more consistent, e.g. we can have a settings defined like this:
```c
/* command i_scroll pans image 1/PAN_FRACTION of screen width/height */
static const int PAN_FRACTION = 5;
```
then in another place we for some reason use an enum to set a single integer:

```c
/* default slideshow delay (in sec, overwritten via -S option): */
enum { SLIDESHOW_DELAY = 5 };
```

Whether we use upper case or lower case for settings should also be made consistent.

**Comment by TAAPArthur** [comment]
@eylles 
My experience seems to contradict the claims you are making. I haven't used every program mentioned, but I used xmonad for sometime and have no recollection of my config breaking on update. Xmonad config files overrides default settings such that if something isn't specified they get the default value which is what I'm proposing.

@N-R-K 
Thank you for the clarification. I see where you are coming from. First I'm fine with auto generating config.h from config.def.h like we have been. Basically after removing static from all the variables, you can continue to use the config.h as you have been and specify everything if you want. I'm just trying to give an extra option. The only opinionated thing I'm forcing on people with this proposal is not breaking your config file on changes (and there are ways to force your build to still fail if you want).

I also think you point on keybindings is valid. I have a different idea for that is independent of this proposal. Basically to have a separate array of user keybindings such that default windows are shadowed by the users ones. In others words if a keybinding (modifier + key sym) is defined in the user config, the default binding will be ignored and if something is bound to an null function it is a no-op (so the binding is basically removed). 

I went ahead an submitted a PR since it may be more productive to talk specifics.

@bakkeby 
>Beyond that you should not expect the configuration file to change that much or that frequently.

Perhaps, but standing on principle that config files should never be broken with good reason. 

>config.h is a C header file, not a plain text configuration file, so you can't just source both and have the config.h settings override the other as you would be defining the same variable twice and compilation would fail. There is not much more to it.

I sent out a PR that does just that. I took advantage of attribute weak. Technically every compiler may not support it so maybe that should be a flag, but I can't name one that doesn't 

I agree with that there are inconsistencies in var style/naming and don't object to fixing them

**Comment by TAAPArthur** [comment]
Also if someone wanted to, we give users on binary distros the same benefit We could optionally allow nxsiv to be compiled as a shared lib (without the config.c I proposed in the PR) and installed to the system. This way regular users could link it with their own config.h and get a nsxiv binary that they could put in their path. This is what xmonad does.

**Comment by bakkeby** [comment]
OK, so it is technically possible to do it this way.

Is it a good way to do it though? Does it make the code easier to read and to maintain?

It is adding a lot of complexity for something that really should not be an issue. 

> Perhaps, but standing on principle that config files should never be broken with good reason.

If that is indeed a principle that is part of the goals of this project then why not skip the half measures and go with a TOML or YAML configuration file?

**Comment by TAAPArthur** [comment]
>Is it a good way to do it though? Does it make the code easier to read and to maintain?

That is indeed the question. Of course I'm going to argue that this is the right direction. If we auto generate what is currently the config_defs.h, then I don't really see any difference in maintenance. And if we don't auto-generate it, I don't think adding that extra line per new config option is that much work. 

> It is adding a lot of complexity for something that really should not be an issue.

I honestly am not getting what is complex about the solution. The PR is open so could you point that what you object to. Aside from the benefit of this issue, I found the state after this patch cleaner as it removes the hack with all the ifdefs and static modifiers (although technically only one of those was needed).

> If that is indeed a principle that is part of the goals of this project then why not skip the half measures and go with a TOML or YAML configuration file?

I didn't consider this a half measure but a full solution. Personally find text based config files to be more work (at least for a language like c) for less flexibility. That is I found strictly worse in every aspect. Slight tangent as it's beyond the scope of this issue but https://github.com/nsxiv/nsxiv/issues/50 is much easier to do with now than with a text based config.

**Comment by bakkeby** [comment]
My gut feeling about this is that we are trying to fix an problem that is not there by introducing a feature nobody asked for.

Following this and the thread in #49 my overall impression is that this proposal has nothing to do with end users in mind but merely TAAPArthur pushing his own agenda so that his build does not break when he switches between git branches (thus re-using the same config.h file).

While the topic title is "Rethinking config.h" any other ideas or suggestions are deemed irrelevant because this is really only about introducing weak references in the default configuration file. The approach seems to be to argue this to death with the aim of forcing others to give in due to discussion fatigue. Honestly it makes me not want to be part of this group after all.

All that said I am not so blind that I do not see that my own rigidness is clouding my judgement regarding this.

If we consider this a development feature and other people in the group find this useful then I suggest that we should just go with it.

**Comment by N-R-K** [comment]
Since we have changed the enums to `const ints`, the current changes in #49 can be done via an external script so we shouldn't have to touch anything in mainline nsxiv. Taap can get what he wants via a shell wrapper, without touching mainline, and I don't believe anyone would have a problem with the script being added to the wiki.

I would like to have this resolved peacefully and I think the external script approach should achive that. Since @bakkeby has maintained "flexipatches" for a good amount of the suckless tools, he has a good understanding of them, so I would value having him on the team. Even if he does not actively work on patches, just having give his opinion/reviews imo is still valuable.

**Comment by eylles** [comment]
looking at this and thinking it again and again, i thought of something that can be done and is perhaps add a make rule and a couple ifdefs something like a config.c that includes config.def.h or config.h and then only serves to override stuff from the default, config.c would not be a regular part of nsxiv nor would be created by the makefile, there would only be checks to see if it exists and if it does then that is what gets used by nsxiv, and that config.c would be only for users that only want to override some defaults.

dunno if that seems like a good compromise or is still a bad idea, i'm not strongly opposed to taap's idea as is, but neither i fully support it as is.

**Comment by TAAPArthur** [comment]
@eylles Isn't the current state of the PR close to what you are thinking? Although with https://github.com/nsxiv/nsxiv/pull/71 and the ban on ifdefs, the PR will have to be modified slightly but the general idea is there.

Also fine with leaving the bulk of the change in the wiki. I believe the one disagreement @N-R-K and I had was if override the OBJS should be given first class support or not. That is should the makefile allow this with addition (which can be done with a little as a 1 character or 1 line change) or should the user have to modify the makefile (which can be done with a 1 line sed command). The same end result would be achieved and from my point of view its the same amount of effort. Do thinking just building all source files is the cleanest solution but involves slightly changing how the autoreload code is handled.

The current PR has the most extreme/invasive changes that make it easiest to take advantage of this change. I was hope people could just point out what they can't accept to determine what gets mainlined vs staying on the wiki.

**Comment by bakkeby** [comment]
I am mostly thinking out loud and have not put a lot of thought into this so not sure how feasible it is, but given that there are ifdefs currently in the config what would it look like if rather than adding the weak references to config.def.h we would instead define the weak references (and thus their defaults) in the respective files instead?

I.e. window configuration goes into window.c, thumbnail settings in thumbs.c, etc.

Then config.def.h could be documentation + settings that are commented out. It can be copied to config.h as it currently is and you would not have to use sed to remove anything. 

Potentially, if it is a source of contention, one could leave some things as static like the keybindings for example, but not sure how that would work in practice.

**Comment by N-R-K** [comment]
@bakkeby taap can already achive his goals via [this](https://github.com/nsxiv/nsxiv/wiki/override-config)

Also I updated the script and renamed the wiki entry to be `override` (with two r) so that the link isn't broken anymore.

**Comment by eylles** [comment]
🤔 bakkeby that is interesting, it could work but begs the question if that would not be more messy in regards of config management?

**Comment by TAAPArthur** [comment]
There was an objection about using non-standard compiler attributes. I believe what you are proposing would force them or at least make it more awkward to add/remove them as it'd be harder to tell what were config vars vs regular ones. I think it would work if we wrapped attribute weak in a macro and allowed users to turn it off/on. It is a larger change than some of the alternatives.

**Comment by bakkeby** [comment]
I know there is a workaround with the script, I'm just exploring other sides of the original idea.

Config maintenance would probably be the same, but this would be more or less transparent to end users (I think).

**Comment by N-R-K** [comment]
Considering that the goal can be achieved via just two sed commands, do we really want to shuffle things around like that?

**Comment by TAAPArthur** [comment]
Other option is to just remove the `static` and `const` modifier instead of adding in attribute weak. In some config.c one could use attribute constructor set default values before main is entered. Wouldn't be too useful for arrays but would allow users to only modify most of the vars they'd want without using `sed`. But for usecases beyond mine, with #50, users could then change they default config options from keybindings if they wanted

**Comment by N-R-K** [comment]
Closing in accordance to https://github.com/nsxiv/nsxiv/pull/49#issuecomment-926265121
