### ISSUE TITLE
crashing on a certain image

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#82]
From https://github.com/nsxiv/nsxiv/pull/75#issuecomment-923347354

[Image in qustion](https://user-images.githubusercontent.com/10392678/134080295-c76880b0-8afd-4882-a9a8-de0f3730b661.png)
> The image I uploaded only crashes if I switch to it in the positive direction (i.e. Space by default) from another image and there have to be many images.

**Comment by mamg22** [comment]
I gave this issue a try on current master `68ddbe2`, I couldn't reproduce by switching to it in a positive direction even with a lot of images, but it did crash when I tried to set zoom to anything lower than 100%.

The only output is:

```
nsxiv: Cannot allocate memory
```

Is this the same output produced in the original report? If true, then continue. Otherwise, then this might be a new a issue.

Also, it doesn't seem to be an issue with just that image, but very small images, this produces an image that crashes with a zoom level somewhere below 100%:

```sh
# 2x2 or similar sizes also cause a crash.
convert any-image-you-have.png -geometry 1x1 troublemaker.png
nsxiv troublemaker.png
```

Anyway, I did some debugging. WIth `gdb`, using `run the-image.png` and setting a breakpoint on `error` got me this stack trace:

```
(gdb) backtrace
#0  error (eval=1, err=12, fmt=0x0) at util.c:65
#1  0x00000000004082d4 in img_render (img=0x418880 <img>) at image.c:627
#2  0x000000000040a6ca in redraw () at main.c:427
#3  0x000000000040b273 in on_keypress (kev=0x7fffffffde40) at main.c:658
#4  0x000000000040bb0a in run () at main.c:828
#5  0x000000000040c2ad in main (argc=2, argv=0x7fffffffe208) at main.c:979
```

The error seems to be somewhere in `img_render`, triggering this check on line 626:

```c
if ((bg = imlib_create_image(dw, dh)) == NULL)
```

Looking at the local variables:

```
(gdb) frame 1
#1  0x00000000004082d4 in img_render (img=0x418880 <img>) at image.c:627
627                             error(EXIT_FAILURE, ENOMEM, NULL);
(gdb) info locals
win = 0x418940 <win>
sx = 0
sy = 0
sw = 1
sh = 1
dx = 508
dy = 123
dw = 0
dh = 0
bg = 0x0
c = {pixel = 18446744073709464800, red = 34944, green = 65, blue = 0, flags = 0 '\000', pad = 0 '\000'}
```

shows `dw` and `dh` being zero, thus trying to create a 0-width, 0-height image, failing and triggering the null check. This seems to be a float-to-int conversion error coming from where those two variables are set.

**Comment by N-R-K** [comment]
> Is this the same output produced in the original report?

Yes, its the same error.

> shows dw and dh being zero, thus trying to create a 0-width, 0-height image, failing and triggering the null check. This seems to be a float-to-int conversion error coming from where those two variables are set.

Aright, I'll take a look into it. Thanks.

**Comment by N-R-K** [comment]
Yeah, it's float to int conversion getting turned into 0 at line 606 and 617.
