### ISSUE TITLE
Feature Request: Fully customizable window title

### ISSUE THREAD

**Issue by OliverLew** [nsxiv/nsxiv#97]
This would be a breaking change, so it's more a discussion than a feature request.

I would like to set up the window title or statusbar in a way similar to `strftime` function (or `date` command, see their man pages) instead of an image info script. I.e., specify the format with a template containing escape sequences, and `nsxiv` will replace those with actual information and show the resulting string.

Since I guess what we want to show in title/statusbar are no more than a few basic properties like filename, size, width, height, index, etc., which are possibly easy to access from within `nsxiv`. Thus, `nsxiv` can prepare a few options and let user pick any combination/format to show.

A possible usage would be like this: if I want to show zoom level, index, total number and file name, the command will be (with our new `-T` switch):

```
nsxiv -T "nsxiv - %z%% (%n/%N) %f"
```

Or do this in `config.def.h`. Maybe use `-B` switch to specify statusbar text, if you ever consider implementing it ...

Pros:

- It's more customizable, and easily extensible in the future (just add more escape sequences).
- It's faster, since no shell script or external command is spawned.

Cons:

- Complicated to implement (or, not that much?)
- It's probably a breaking change, and it breaks user's configuration. It won't break that much if we only change the window title.

**Comment by N-R-K** [comment]
One other user requested fully customizable window title (https://github.com/nsxiv/nsxiv/issues/58)

What I have been thinking about is adding `title-info` similar to `image-info`. We pass all relevant info to the shell script as arguments and the user can then do whatever they want with it.

As for backwards compatibility, we only care about backwards compatibility with `sxiv`. Since the window title was an nsxiv addition, I don't think we mind breaking it if we can have something more extensible in return.

**Comment by N-R-K** [comment]
@OliverLew I just realized that I failed to address your request properly. What you're asking for is not to add an external script but to do it internally instead.

I think there's a couple problem with this

* It will limit what users can do to only the values we allow.
* I suspect it will actually take more code to implement. Since we already have code for `image-info`, refactoring those to also support `title-info` will be easier.

So if we are to allow more customizable win title, we should just let it be *fully* customizable by just letting users do whatever they want in a script similar to `image-info` instead of limiting it to certain values.

**Comment by OliverLew** [comment]
I was indeed thinking about some radical changes (actually, even deprecating `image-info` for this method), and wasn't expecting you devs to accept it at all.

The idea was that I think an external script might be an overkill for this. As long as there is enough common options for the  format string, it should suffice.

I'm probably wrong, for example if someone want to show some EXIF data, that would be easy for a script,  but not so doing it internally. Also, scripts will handle cases like empty values better. E.g., in `ncmpc(pp)`, we can customize the song list format similarly, and it's hard to fine tune when to show something and when not to.

So I am okay with the issue title change, a `title-info` is better.

**Comment by TAAPArthur** [comment]
I think this is an interesting idea. If I could take a little creative liberty, you could do it pretty simply. 
What I'm imaging is something like `nsxiv -T 'nsxiv - $ZOOM_LEVEL ($FILE_INDEX/$FILE_CNT) $FILE_NAME'`. We could simply spawn a shell command and in that environment give a list of useful properties and just use whatever it gives us (or the first N chars) for that as the title. I'd vote for creating this env for the keyhandler and any other external cmd we spawn too because why not.
